version: '3.1'
services:
  teamspeak:
    image: teamspeak
    container_name: teamspeak
    restart: always
    volumes:
      - /opt/teamspeak/data:/var/ts3server
    ports:
      - 9987:9987/udp
      - 10011:10011
      - 30033:30033
    environment:
      TS3SERVER_LICENSE: accept
