#docker-compose.yml

version: "3"

services:
  bitwarden:
    container_name: bitwarden
    image: bitwardenrs/server
    restart: always
    volumes:
      - ./bw-data:/data
      - ./ssl:/ssl
    ports:
        - 8443:80
    environment:
      WEBSOCKET_ENABLED: "true" # Required to use websockets
      ROCKET_TLS: '{certs = "/ssl/vault.crt", key = "/ssl/vault.key"}'
      SIGNUPS_ALLOWED: 'false'
