version: "3"
services:
  valheim:
    container_name: valheim_iii
    image: mbround18/valheim:latest
    ports:
      - 4456:4456/udp
      - 4457:4457/udp
      - 4458:4458/udp
    environment:
      - PORT=4456
      - NAME="Friendos and Vikings III"
      - WORLD="Friendos III"
      - PASSWORD="hello"
      - TZ=America/New_York
      - PUBLIC=1
    volumes:
    - ./valheim/saves:/home/steam/.config/unity3d/IronGate/Valheim
    - ./valheim/server:/home/steam/valheim
