---
version: "2"
services:
  bookstack:
    image: linuxserver/bookstack
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - DB_HOST=bookstack_db
      - DB_USER=bookstack
      - DB_PASS=Bookst4ckDB
      - DB_DATABASE=bookstackapp
      - VIRTUAL_HOST=wiki.arneman.home
    volumes:
      - /opt/bookstack/config:/config
    ports:
      - 6875:443
    restart: unless-stopped
    depends_on:
      - bookstack_db

  bookstack_db:
    image: linuxserver/mariadb
    container_name: bookstack_db
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=rob0t1rk
      - TZ=America/New_York
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=Bookst4ckDB
    volumes:
      - /opt/bookstack/config:/config
    restart: unless-stopped
