version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      # - "80:80/tcp"
      # - "443:443/tcp"
    env_file:
      - pihole.env
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:pihole.arneman.home,pihole,pi.hole
      - traefik.frontend.entryPoints=http
      - traefik.port=80
    networks:
      - traefik
    # Volumes store your data between container upgrades
    volumes:
       - './etc-pihole/:/etc/pihole/'
       - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    dns:
      - 127.0.0.1
      - 1.1.1.1
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    # cap_add:
      # - NET_ADMIN
    restart: unless-stopped

networks:
    traefik:
        external: true