version: "3"
services:
  # Deluge - torrent downloader
  deluge:
    image: linuxserver/deluge:latest
    container_name: deluge
    network_mode: "host"
    environment:
      - PUID=0
      - PGID=0
      - UMASK_SET=022
      - TZ=America/New_York
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:deluge.arneman.home,deluge,downloads,downloads.arneman.home
      - traefik.frontend.entryPoints=http
      - traefik.port=8112
    # networks:
    #   - traefik
    ports:
      - 8112:8112
      - 45000:45000
      - 58846:58846
    volumes:
      - ./deluge/config:/config
      - "mediamount:/media"
    restart: unless-stopped

  # Radarr - Movie indexer
  radarr:
    image: linuxserver/radarr:nightly
    container_name: radarr
    environment:
      - PUID=0
      - PGID=0
      - UMASK_SET=022
      - TZ=America/New_York
    ports:
      - 7878:7878
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:radarr.arneman.home,radarr,movies,movies.arneman.home
      - traefik.frontend.entryPoints=http
      - traefik.port=7878
    networks:
      - traefik
    volumes:
      - ./radarr:/config
      - "mediamount:/media"
    restart: unless-stopped

  # Sonarr - Television indexer
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=0
      - PGID=0
      - UMASK_SET=022
      - TZ=America/New_York
    ports:
      - 8989:8989
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:sonarr.arneman.home,sonarr,tv,tv.arneman.home
      - traefik.frontend.entryPoints=http
      - traefik.port=8989
    networks:
      - traefik
    volumes:
      - ./sonarr:/config
      - "mediamount:/media"
    restart: unless-stopped

  # Jackett - torrent indexer for Radarr/Sonarr
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - UMASK_SET=022
      - TZ=America/New_York
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:jackett.arneman.home,jackett
      - traefik.frontend.entryPoints=http
      - traefik.port=9117
    networks:
      - traefik
    volumes:
      - ./jackett:/config
    restart: unless-stopped

  # Tautulli - Plex Stats (formally PlexPy)
  tautulli:
    image: linuxserver/tautulli
    container_name: tautulli
    environment:
      - UMASK_SET=022
      - TZ=America/New_York
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:plexpy.arneman.home,plexpy
      - traefik.frontend.entryPoints=http
      - traefik.port=8181
    networks:
      - traefik
    volumes:
      - ./tautulli:/config
    restart: unless-stopped

  dizquetv:
    container_name: dizquetv
    ports:
      - '8000:8000'
    volumes:
      - './dizquetv:/home/node/app/.dizquetv'
    image: 'vexorian/dizquetv:latest'

  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin
    network_mode: "host"
    restart: "unless-stopped"
    volumes:
      - ./jellyfin/config:/config
      - ./jellyfin/cache:/cache
      - /mnt/sauron/Media:/media

  jfa-go:
      container_name: jfa-go
      ports:
          - '8056:8056'
      volumes:
          - './jfa-go:/data'
          - './jellyfin:/jf'
          - '/etc/localtime:/etc/localtime:ro'
      image: hrfee/jfa-go


volumes:
  mediamount:
    driver: local
    driver_opts:
      type: nfs
      o: addr=sauron.arneman.home,nolock,soft,rw
      device: ":/Media"

networks:
    traefik:
        external: true
