version: '3'
services:
    assetto-server-manager:
        image: seejy/assetto-server-manager:latest
        container_name: assetto
        restart: unless-stopped
        environment:
            - PUID=1000
            - PGID=1000
        ports:
            # the port that the server manager runs on
            - "8772:8772"
            # the port that the assetto server runs on (may vary depending on your configuration inside server manager)
            - "9600:9600"
            - "9600:9600/udp"
            # the port that the assetto server HTTP API runs on.
            - "8081:8081"
            # you may also wish to bind your configured UDP plugin ports here.
            - "50042:50042"
        volumes:
            # volume mount the entire server install so that
            # content etc persists across restarts
            - ./server-manager:/home/assetto/server-manager/assetto
            - ./assetto:/assetto/

            # volume mount the config
            - ./config.yml:/home/assetto/server-manager/config.yml