version: '3'

services:
  db:
    container_name: nextcloud_mariadb
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql
    env_file:
      - db.env
    networks:
      - internal

  redis:
    container_name: nextcloud_redis
    image: redis:alpine
    restart: always
    networks:
      - internal

  cron:
    container_name: nextcloud_cron
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      - nextcloud:/var/www/html
    entrypoint: /cron.sh
    networks:
      - internal
    depends_on:
      - db
      - redis

  app:
    container_name: nextcloud
    image: nextcloud:latest
    restart: always
    volumes:
      - nextcloud:/var/www/html
      - storagemount:/storage
    environment:
      - MYSQL_HOST=db
      - REDIS_HOST=redis
    networks:
      - traefik
      - internal
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:cloud.arneman.me
      - traefik.frontend.entryPoints=http,https
    env_file:
      - db.env
    depends_on:
      - db
      - redis

volumes:
  db:
  nextcloud:
  storagemount:
    driver: local
    driver_opts:
      type: nfs
      o: addr=freenas.arneman.home,nolock,soft,rw
      device: ":/mnt/FreeNAS-Vol/Storage"

networks:
  internal:
  traefik:
    external: true
