version: "2.1"
services:
  nextcloud:
    image: linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - TZ=America/New_York
    volumes:
      - ./appdata:/config
      - ./data:/data
      - storagemount:/storage
      - mediamount:/media
    networks:
      - traefik
      - internal
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:cloud.arneman.me,cloud.arneman.home,cloud
      - traefik.frontend.entryPoints=http,https
    ports:
      - 8443:443
    restart: unless-stopped

volumes:
  db:
  nextcloud:
  storagemount:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.0.0.241,nolock,soft,rw
      device: ":/Storage"
  mediamount:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.0.0.241,nolock,soft,rw
      device: ":/Media"

networks:
  internal:
  traefik:
    external: true
