version: "3"
services:
  folding-at-home:
    image: yurinnick/folding-at-home
    container_name: folding-at-home
    environment:
      - USER=marneman
      - TEAM=0
      - ENABLE_GPU=false
      - ENABLE_SMP=true
    ports:
      - 7396:7396
      - 36330:36330
    restart: unless-stopped
