version: '3.4'
services:
  jenkins:
    container_name: 'jenkins'
    image: jenkinsci/blueocean
    ports:
      - '8081:8080'
      - '50000:50000'
    labels:
      - traefik.enable=true
      - traefik.web.frontend.rule=Host:jenkins.arneman.me,jenkins
      - traefik.web.port=8080
    networks:
      - traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - 'jenkins_home:/var/jenkins_home'

volumes:
  jenkins_home:
    driver: local

networks:
    traefik:
        external: true
