version: '3'
services:
  openvpn:
    network_mode: "host"
    cap_add:
     - NET_ADMIN
    image: kylemanna/openvpn
    container_name: openvpn
    ports:
     - "1194:1194/udp"
     - "5555:5555"
    # networks:
    #   vpn:
    #     ipv4_address: 172.23.0.2
    volumes:
     - ./conf:/etc/openvpn
    restart: unless-stopped

  openvpn-monitor:
    container_name: openvpn-monitor
    image: mumblepins/openvpn-monitor
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:vpnstatus,vpnstatus.arneman.home
      - traefik.frontend.entryPoints=http
    networks:
      traefik:
      # vpn:
      #   ipv4_address: 172.23.0.3
    env_file:
      monitor.env
    restart: unless-stopped

networks:
  # vpn:
  #   ipam:
  #     config:
  #       - subnet: 172.23.0.0/16
  traefik:
    external: true