version: '3'

services:
  db:
    image: mariadb
    container_name: matomo_db
    command: --max-allowed-packet=64MB
    restart: always
    networks:
      - matomo
    volumes:
      - db:/var/lib/mysql
    env_file:
      - ./db.env
    restart: unless-stopped

  app:
    image: matomo:latest
    container_name: matomo
    restart: always
    links:
      - db
    networks:
      - matomo
      - traefik
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:stats.arneman.me
      - traefik.frontend.entryPoints=http,https
    volumes:
      - ./config:/var/www/html/config:rw
      - ./logs:/var/www/html/logs
      - matomo:/var/www/html
    environment:
      - MATOMO_DATABASE_HOST=db
    env_file:
      - ./db.env
    restart: unless-stopped

volumes:
  db:
  matomo:

networks:
    traefik:
        external: true
    matomo: