version: '3'

services:
  db:
    image: mariadb
    container_name: matomo_db
    command: --max-allowed-packet=64MB
    restart: always
    networks:
      - matomo
    volumes:
      - db:/var/lib/mysql
    # environment:
    #   - MYSQL_ROOT_PASSWORD=
    env_file:
      - ./db.env

  matomo:
    image: matomo:fpm-alpine
    container_name: matomo_app
    restart: always
    links:
      - db
    networks:
      - matomo
    volumes:
      - ./config:/var/www/html/config:rw
      - ./logs:/var/www/html/logs
      - matomo:/var/www/html
    environment:
      - MYSQL_HOST=db
    env_file:
      - ./db.env

  web:
    image: nginx:alpine
    container_name: matomo_web
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.backend=matomo"
      - "traefik.frontend.rule=Host:stats,stats.arneman.home,stats.arneman.me"
      - "traefik.port=80"
    networks:
      - traefik
      - matomo
    volumes:
      - matomo:/var/www/html:ro
      # see https://github.com/matomo-org/matomo-nginx
      - ./matomo.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 8081:80

volumes:
  db:
  matomo:

networks:
    traefik:
        external: true
    matomo: