version: '3'

services:
  db:
    image: mariadb
    container_name: matomo_db
    command: --max-allowed-packet=64MB
    networks:
      - matomo
    volumes:
      - db:/var/lib/mysql
    env_file:
      - ./db.env
    restart: unless-stopped

  app:
    image: matomo:fpm-alpine
    container_name: matomo
    links:
      - db
    networks:
      - matomo
    volumes:
      - ./config:/var/www/html/config:rw
      - ./logs:/var/www/html/logs
      - matomo:/var/www/html
    environment:
      - MATOMO_DATABASE_HOST=db
    env_file:
      - ./db.env
    restart: unless-stopped

  web:
    image: nginx:alpine
    container_name: matomo_web
    restart: unless-stopped
    networks:
      - matomo
      - traefik
    volumes:
      - matomo:/var/www/html:ro
      # see https://github.com/matomo-org/matomo-nginx
      - ./matomo.conf:/etc/nginx/conf.d/default.conf:ro
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:stats.arneman.me,stats.arneman.home,stats
      - traefik.frontend.entryPoints=http,https
    ports:
      - 8082:80

volumes:
  db:
  matomo:

networks:
  traefik:
    external: true
  matomo: