version: "3"
services:
  terraria:
    container_name: terraria
    image: ryshe/terraria:latest
    stdin_open: true # docker run -i
    tty: true # docker run -t
    environment:
      - WORLD_FILENAME=world.wld
      - CONFIGPATH=config.json
    ports:
      - 7777:7777
    volumes:
      - ./world:/root/.local/share/Terraria/Worlds
    restart: unless-stopped