version: "3"

services:
  db:
    container_name: photoview_db
    image: mariadb:10.5
    restart: always
    env_file: db.env
    volumes:
      - db_data:/var/lib/mysql

  photoview:
    container_name: photoview
    image: viktorstrate/photoview:2
    restart: unless-stopped
    ports:
      - "8000:80"
    depends_on:
      - db

    env_file: .env

    volumes:
      - api_cache:/app/cache

      # Change This: to the directory where your photos are located on your server.
      # If the photos are located at `/home/user/photos`, then change this value
      # to the following: `/home/user/photos:/photos:ro`.
      # You can mount multiple paths, if your photos are spread across multiple directories.
      - /mnt/sauron/Storage/Photos:/photos:ro
      - /mnt/sauron/Storage/Photos/A6000:/test:ro

volumes:
  db_data:
  api_cache:
